### ISSUE TITLE
Recommend appropriate lengths for the text fields

### ISSUE THREAD

**Issue by mwpowellhtx** [cplate/oauth2#1]
When mapping to database, can you suggest some appropriate character lengths? I'm only guessing, things like encryption keys are probably NVARCHAR(256). Also, I'm assuming that the fields are, for the most part, NOT NULL, in terms of SQL? Thank you...

**Comment by cplate** [comment]
Well, I didn't spend any time trying to nail those details down, as I just let EF generate the database for me and used it as is.  I'd suggest looking at the OAuthDbInitializer class that inserts some seed data.  From that you can see what fields/properties you have control over and thus you can size them as you see fit.  Other fields, like those in the Nonce class, are generated by DotNetOpenAuth and I'm not sure about reasonable sizes those.  In the end, if row size is a concern, you might just want to make them as small as you like and then see if those lengths cause problems and subsequently enlarge them.

Sorry I can't be of more help.  Unfortunately I haven't touched this or really even thought about it since I put it out here as I've been pulled in other directions.

**Comment by mwpowellhtx** [comment]
No worries. I appreciate the feedback.
